### PR TITLE
Create starsPrinting

### PR DESCRIPTION
**Pull request by aryavrma**
Added Stars Printing in Java. Please Accept PR

### CODE REVIEW

**Comment by abirbhattacharya82** [comment]
Just take the value of n as input and we are good to go. Make the changes and create the PR.

**Review by aryavrma — COMMENTED** [review]
Updated it. Please check out

**Comment by abirbhattacharya82** [comment]
There is an error. Put the import statement.

**Review by aryavrma — COMMENTED** [review]
Done

**Comment by abirbhattacharya82** [comment]
Do you want to contribute it towards Hacktoberfest??

**Comment by aryavrma** [comment]
Yes

**Pull request merged**
